server:
  port: 7000
  servlet:
    context-path: /ad-sponsor

spring:
  application:
    name: eureka-ad-client-sponor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/adData?autoReconnect=true
    username: root
    password: root
    tomcat:
      max-active: 4
      initial-size: 2
      min-idle: 2
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
